name: "01 🤖 要件定義 (Copilot Coding Agent)"
description: "要望を入力。要件定義までをCopilotに自動展開させる（このIssueでは要件定義のみ実施）"
title: "[要件定義] <機能名を記入>"
labels: ["enhancement", "autogen"]
assignees: ["copilot"]

body:
    - type: input
      id: project_identifier
      attributes:
          label: プロジェクト名・機能名・設計名（必須・英数字/ハイフンのみ）
          description: |
              この値を元に `docs/{project_identifier}/requirements.md` として要件・設計ファイルが作成されます。
              例: `payment-history` → `docs/payment-history/requirements.md`
              設計や他の成果物も同じディレクトリを使います。
          placeholder: 例）payment-history
      validations:
          required: true

    - type: textarea
      id: brief
      attributes:
          label: 要望（必須・1～3行でOK）
          description: 例）「購入履歴を検索・フィルタできる画面が欲しい」「プロフィール編集に2FAを必須化したい」
          placeholder: |
              例）「ポイントを使って支払いできるようにしたい」
      validations:
          required: true

    - type: textarea
      id: agent_instructions
      attributes:
          label: "⛳ エージェント向け明示指示"
          description: "この内容はIssue本文に含まれます（必要に応じて編集可）。"
          render: markdown
          value: |
              ---
              ### ⛳ エージェント向け明示指示
              以下を**Markdown**で生成し、このIssueにコメントとして貼り付け、併せて `docs/{project_identifier}/requirements.md` として新規作成しPRに含めてください。
              - `{project_identifier}` には上記「プロジェクト名・機能名・設計名」の値をそのまま使ってください（例: `payment-history` なら `docs/payment-history/requirements.md`）。
              - 他の成果物がある場合は、同じディレクトリ配下に格納してください（例: `docs/{project_identifier}/*.md`）

              1) 背景・目的（1段落）
              2) スコープ / 非スコープ（箇条書き）
              3) ステークホルダー & 主要ユースケース（簡潔）
              4) 機能要件（EARS形式で最大10件：Ubiquitous / State-driven / Event-driven）
              5) ユーザーストーリー（INVEST、各ストーリーにMoSCoW優先度）
              6) 受け入れ基準（各ストーリー3〜5件、GherkinのGiven/When/Then）
              7) 非機能要件（ISO/IEC 25010にマップし**数値で**定量化。例：p95応答≦200ms）
              8) データ & APIドラフト（主要エンティティ一覧、OpenAPIスケルトン）
              9) リスク / 依存関係 / 制約
              10) Assumptions / Open Questions（仮定と要確認事項）
              11) 成功指標（SMART）と計測方法

              追加要件：
              - 曖昧語は禁止（「高速」→ *p95=200ms以下* のように **必ず数値化**）
              - 例外/エラー/雨天シナリオを最低1件ずつ含める
              - PRの説明文は日本語で記載してください。
      validations:
          required: false

    - type: checkboxes
      id: ack
      attributes:
          label: 実行前チェック
          options:
              - label: Issue 作成後に **Copilot が自動で担当者に割り当て** られます（確認済み）
                required: true
